Feature: Show the number of selected records on the wizard
OpenG2P/openg2p-erp pull request #43
Opened 2020-05-13 13:33 UTC by atularvind

This PR will adds a feature to show number of records selected records on the Create Disbursement & Register Into Program wizard.

2020-05-13 21:42 UTC, saltonmassally commented
@atularvind can u please attach screenshots of wizard?

2020-05-18 08:56 UTC, atularvind commented
@saltonmassally, here it is
![image](https://user-images.githubusercontent.com/1876476/82193720-6966e200-9913-11ea-9e96-68a54d11d99f.png)
![image](https://user-images.githubusercontent.com/1876476/82193755-78e62b00-9913-11ea-9dc0-3eeb80e021f2.png)

2020-05-19 08:18 UTC, saltonmassally requested changes

2020-05-19 08:18 UTC, saltonmassally commented on openg2p_disbursement/wizard/batch_from_selected_beneficiary.py
> +        self.all_record_count = self.env['openg2p.beneficiary'].search_count([])
@atularvind use should be passing active_domain like I do in the code to filter beneficiaries to act on

2020-05-19 08:18 UTC, saltonmassally commented on openg2p_disbursement/wizard/batch_from_selected_beneficiary.py
> +    all_record_count = fields.Integer('All Record Count', compute="_compute_selected_record")
rename to active_domain_record_count

2025-09-27 14:38 UTC, closed without merging